name: penguin-noses
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - name: Setup R
        uses: r-lib/actions/setup-r@master
        
      - uses: actions/checkout@v2
        
      - name: Do the job!
        run: |
          R -e 'install.packages("renv")'
          Rscript penguin_analysis.R
          cml-publish my_penguin_plot.png --md > report.md
          cml-send-comment report.md
